# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ww < Formula
  desc "Workspace-aware git worktree manager"
  homepage "https://github.com/yoskeoka/ww"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoskeoka/ww/releases/download/v0.3.0/ww_0.3.0_darwin_amd64.zip"
      sha256 "c7f73cc49bb85ed286debe2f686db26f7e84cd2a0b0336909ce87d3cea692d47"

      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoskeoka/ww/releases/download/v0.3.0/ww_0.3.0_darwin_arm64.zip"
      sha256 "ee7d69178f1b9186f2d076f6a21d8b25581b1a1607480d047ea6ec9c771ec132"

      define_method(:install) do
        bin.install "ww"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoskeoka/ww/releases/download/v0.3.0/ww_0.3.0_linux_amd64.tar.gz"
      sha256 "855d051258debaf34482489e7e2d8e3c4f8172b13eee743559efd8ab0aa4fe41"
      define_method(:install) do
        bin.install "ww"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoskeoka/ww/releases/download/v0.3.0/ww_0.3.0_linux_arm64.tar.gz"
      sha256 "62a45f57c4334f77e31c24d6a1eff8538034abd245703791464886d41eef0bb6"
      define_method(:install) do
        bin.install "ww"
      end
    end
  end
end
